name = "Federated WebRing"
description = "Default config of Federated WebRing!"
host = "localhost"

[database_credentials]
host = "localhost"
user = "webring"
password = "change me!"
dbname = "webring"
port = 5432
timezone = "Europe/Paris"

[redis_credentials]
host = "localhost"
port = 6379
password = ""
