name = "Federated WebRing"
description = "Default config of Federated WebRing!"

[database_credentials]
host = "localhost"
user = "webring"
password = "change me!"
dbname = "webring"
port = 5432
timezone = "Europe/Paris"
